<?php

use yii\db\Migration;

/**
 * Class m240420_094711_insert_data_cities_table
 */
class m240420_094711_insert_data_cities_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->insert('cities',['name'=> 'અડાલજ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'અંબાપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'અમીયાપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'આદરજ મોટી','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'આદીવાડા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'આલમપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ઈન્દ્રોડા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ઈસનપુર મોટા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ઉનાવા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ઉવારસદ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કુડાસણ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કરાઈ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કોટેશ્વર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કોબા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કોલવડા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ખોરજ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ગલુદણ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ગીયોડ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ચેખલારાણી','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ચંદ્રાલા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ચીલોડા (ડભોડા)','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ચીલોડા (નરોડા) ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'છાલા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'જમીયતપુરા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'જલુંદ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'જાખોરા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ઝુંડાલ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ટીંટોડા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ડભોડા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'તારાપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'દંતાલી','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'દશેલા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'દોલારાણા વાસણા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ધણપ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ધોળાકુવા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'નભોઈ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'નવા ધર્મપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પેથાપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પુન્દ્રાસણ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પ્રાંતીયા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પાલજ ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પીંડારડા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પીપલજ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પીરોજપુર','taluka_id' => '11','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પોર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'બાસણ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'બોરીજ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ભાટ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ભોયણ રાઠોડ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મગોડી','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મેદરા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મુબારકપુરા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મહુંદ્રા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'માધવગઢ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ર઼ણાસણ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'રતનપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'રુપાલ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'રાજપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'રાંદેશણ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'રાંધેજા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'રાયપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'રાયસણ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'લેકાવાડા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'લવારપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'લીંબડીયા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વડોદરા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વલાદ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વાંકાનેરડા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વાવોલ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વાસણા હડમતીયા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વાસન','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વીરા તલાવડી','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'શેરથા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'શાહપુર','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'શીહોલી મોટી','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સુઘડ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સરગાસણ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સર઼ઢવ','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સાદરા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સોનારડા','taluka_id' => '11','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સોનીપુર','taluka_id' => '11','distric_id' => '2']);


        $this->insert('cities',['name'=> 'અંગુથલા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'અંતોલી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'અમરાજીના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'અરજણજીના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'આંત્રોલી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ઇસનપુર ડોડીયા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ઉદણ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'એહમદપુરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ઓત઼મપુરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કડજોદરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કડાદરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કંથારપુરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કનીપુર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કમાલબંધ વાસણા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કરોલી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કલ્યાણજીના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કુષ્ણનગર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'કોદરાલી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ખાખરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ખાડીયા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ખાનપુર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ચેખલા પગી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ચાંદા/જેસાના મુવા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ચામલા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ચિસકારી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'જલુન્દ્રા નાના','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'જલુન્દ્રા મોટા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'જાલીયા મઠ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'જીંડવા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'જીવાજીની મુવાડી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ઝાંક','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ડુમેચા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ડેમાલીયા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'થડાકુવા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'દેવકરણના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'દહેગામ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'દોડ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ધમીજ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ધારીસણા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'નજુપુરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'નવાનગર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'નાંદોલ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પલ્લાના મ઼ઠ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પસુણીયા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પહાડીયા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પાટના કુવા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પાલુન્દ્રા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પાલૈયા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'પીપલજ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'બદપુર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'બહિયલ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'બાબરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'બારડોલી બારીયા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'બારડોલી ક઼ાંઠી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'બારીયા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'બીલમણા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'ભાદરોડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મેઘરજના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મહુડીયા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'માછંગ નાની','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'માછંગ મોટી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મીઠાના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મીર઼ઝાપુર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મીરાપુર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મોટી પાવડી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મોતીપુરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મોરાલી મોટી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'મોસમપુર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'રખીયાલ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'રામનગર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'લવાડ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'લીહોડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વટવા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વડવાસા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વડોદ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વર્ધાના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વેલપુરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વાસણા ચૌધરી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વાસણા રાઠોડ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'વાસણા સોગઠી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'શિયાપુરા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'શિયાવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સગદલપુર','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સુજાના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સલકી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સાણોદા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સાંપા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સાંબેલા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સામેત્રી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'સાહેબજીના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'હર઼ખજીના મુવાડા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'હરસોલી','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'હાથીજણ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'હાલીસા','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'હિલોલ','taluka_id' => '10','distric_id' => '2']);
        $this->insert('cities',['name'=> 'હિલોલ વાસણા','taluka_id' => '10','distric_id' => '2']);


        $this->insert('cities',['name'=> 'આનંદપુરા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઉકરડી','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઉઘરોજપુરા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઉધરોજ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઐંદલા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઓડકી','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કડવાસણ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કૂણપુર','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કરશનપુરા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાચરોલ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાનપુરા (શીણજ)','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જાલીસણા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝાંઝરવા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ટ્રેન્ટ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ડઢાણા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઢેઢાસણા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દાલોદ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નવાગામ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાના ઉભડા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાયકપુર','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'માંડલ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'માનપુરા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મીઠાપુર','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રખીયાના','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રીબડી','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વનપરડી','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાસણા (કૂણપુર)','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વિંછણ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વિઠલાપુર','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વિન્ઝુવાડા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શેર','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શીણજ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાદરા','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સીતાપુર','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સોલગામ','taluka_id' => '8','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હાંસલપુર (બે.)','taluka_id' => '8','distric_id' => '1']);

        $this->insert('cities',['name'=> 'અબાસણા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'અમરપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'અશોકનગર','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઈન્દ્રપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઉમેદપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઓઢવ','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કુકવાવ','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાંઝ','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાંત્રોડી','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કોઈન્તીયા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગુંજાલા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગમાનપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગીતાપુર','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઘટીસણા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઘેલડા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'છનીયાર','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જેઠીપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જસપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ડાંગરવા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ડાભસર','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દેકાવાડા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દેત્રોજ','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દામોદરીપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નદીશાળા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાથપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાના કરણપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાની રાન્તાઈ','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પનાર','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ફતેહપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બાન્ટાઈ','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બામરોલી','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બોસ્કા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભંકોડા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભગાપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભોયણી','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભોયણીપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મદ્રીસણા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મારૂસણા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોટા કર઼ણપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોટીરાન્તાઈ','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રતનપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રૂદાતલ','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાજપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રામપુરા(ભંકોડા)','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાસણા(છનીયાર)','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શિહોર','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શોભાસણ','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સંગપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સદાતપુરા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સુંવાળા','taluka_id' => '9','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હઠીપુરા','taluka_id' => '9','distric_id' => '1']);



        $this->insert('cities',['name'=> 'અસલગામ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઉખલોડ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઓગાણ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કુમરખાણ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કમીજલા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કરકથલ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કરણગઢ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કરીયાલા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાંકરાવાડી','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાદીપુર','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાનપુરા (દશ)','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાયલા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાલીયાણા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કોક઼તા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખેગારીયા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખુડદ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગોરૈયા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચણોઠીયા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચુનીનાપુરા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જક્શી','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જખવાડા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જેતાપુર','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જુનાપાઘર','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જાલમપુરા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝેઝરા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ડુમાણા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'થુલેટા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'થોરીમુબારક','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'થોરીવડગાસ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દેવપુરા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દસલાણા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ધાકડી','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ધોડા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નદીયાણા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાની કુમાદ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાની-કિશોલ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નિલકી','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભડાણા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભાવડા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભોજવા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મેમદપુરા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મેલજ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોટીકુમાદ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોટી-કિશોલ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રંગપુર','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રુપાવટી','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રહેમલપુર','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'લીંબડ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'લીયા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વેકરીયા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વ઼ડગાસ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વણી','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વનથળ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વલાણા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વસવેલીયા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાસ઼ણ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાંસવા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વિરમગામ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શાહપુર','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શિયાલ ','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શીવપુરા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સચાણા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સબલપુરા','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સરસાવડી','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સોંકલી','taluka_id' => '7','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હાંસલપુર-(શે.)','taluka_id' => '7','distric_id' => '1']);

        //સાણંદ-6
        $this->insert('cities',['name'=> 'અણદેજ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'અણિયાળી','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઇયાવા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઉપરદળ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કુંડલ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કલાણા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કુંવાર','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાણેટી','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કોદાળીયા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કોલટ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખીચા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખોડા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખોરજ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગરોડીયા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગોધાવી','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગોરજ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગોવિંદા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચેખલા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચરલ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચાંગોદર','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'છારોડી','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જુડા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જુવાલ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝાંપ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝોલાપુર','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ડરણ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'તેલાવ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'તાજપુર','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દદુકા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દોદર','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નવાપુરા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાની દેવતી','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નારણપુરા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નિઘરાડ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નોર્થકોટપુરા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પલવાડા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પીંપણ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ફાંગડી','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બકરાણા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બોળ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભાવનપુર','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મખીયાવ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મટોડા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મણીપુર','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મેલાસણા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'માણકોલ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોટી દેવતી','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોડાસર','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોરૈયા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રેથલ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રુપાવટી','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રામપુરા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'લેખંબા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'લોદરીયાળ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વનાળીયા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વસોદરા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાસણા(ઇયાવા)','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાસણા(ચાચરવાડી)','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વિછીંયા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વિરોચનનગર','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શેલા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શીયાવાડા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સરી','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાણંદ ગામ','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સોયલા','taluka_id' => '6','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હીરાપુર','taluka_id' => '6','distric_id' => '1']);

        // સિટી દસ્ક્રોઈ -1
        $this->insert('cities',['name'=> 'અસલાલી','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઇસ્ટોલાબાદ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઉન્દેલ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'એણાસણ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઓડ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કુંજાડ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કઠવાડા','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કણભા','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કુબડથલ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કુહા','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાણીયેલ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાસીન્દા','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગતરાડ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગેરતનગર','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગેરતપુર','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગામડી','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગીરમ઼થા','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગોવિંદડા','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચવલજ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચાંદીયેલ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચોસર','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જેતલપુર','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝાણુ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ટીબાં','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દેવડી','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ધામતવાણ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નવરંગપુરા','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નવાપુરા','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાઝ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાંદેજ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પરઢોલ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પશુંજ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પાલડી-કાંકજ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બડોદરા ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બાકરોલ-બુજરંગ','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બારેજડી','taluka_id' => '1','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બારેજા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બીબીપુર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બીલાસીયા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભરકુંડા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભુવાલ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભુવાલડી','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભાત','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભાવડા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મેમદપુર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મહીજડા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મીરોલી','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રણોદરા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રોપડા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'લાલપુર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વડોદ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વસઇ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વહેલાલ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાંચ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વિસલપુર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સીગરવા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હુકા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સહરણીયાવ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હીરાપુર','taluka_id' => '5','distric_id' => '1']);


        
        //ધોળકા
        $this->insert('cities',['name'=> 'અંઘારી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'અરણેજ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'આનંદપુરા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'આંબેઠી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'આંબલીયારા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'આંબારેલી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઇંગોલી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઉત્તેલીયા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કરીયાણા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કલ્યાણપુર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કેશરગઢ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાદીપુર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાલીયાપરા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કોઠ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કૌકા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખરાંટી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખાત્રીપુર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખાનપુર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગુંદી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગાણેસર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગાણોલ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગીરંદ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઘોળકા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઘોળી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચંડીસર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચલોડા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગોઘનેશ્વર(જલાલપુર)','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વજીફા(જલાલપુર)','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જવારજ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જાખડા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ડડુસર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ત્રાસંદ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નેસડા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાનીબોરુ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પાલડી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પીસાવાડા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બેગવા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બદરખા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભેટાવાડા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભુભલી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભુરખી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભોળાદ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મુંજપુર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મફલીપુર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોટીબોરુ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રનોડા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રુપગઢ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાજપુર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રામપુર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રામપુરા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાયપુર','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'લાણા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'લોલીયા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વેજલકા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વટામણ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વારણા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાલથેરા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાસણા કેલીયા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વીરડી ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વીરપુર  ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વૌઠા ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શેખડી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શીયાવાડા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સમાણી','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સરગવાળા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સરોડા','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સહીજ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાથળ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સસીંઘરેજ','taluka_id' => '3','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સીમેજ','taluka_id' => '3','distric_id' => '1']);

        //બાવળા-2
        $this->insert('cities',['name'=> 'અમીપુરા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'આદરોડા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કેરાલા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કલ્યાણગઢ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કવલા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કેસરડી','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાણોતર','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાલીવેજી','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કોચરીયા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગુંદાનાપરા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગાંગડ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચિયાડા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'છબાસર ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જુવાલ-રૂપાવટી','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝેકડા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઢેઢાલ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દુમાલી','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દુર્ગી','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દેવ ધોલેરા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દેવડથલ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દહેગામડા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ધનવાડા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ધીંગડા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાનોદરા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બગોદરા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બલદાણા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બાવળા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભામસરા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભાયલા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મૈટાલ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મેણી ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મેમર','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મીઠાપુર','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રજોડા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રુપાલ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાણેસર','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાશમ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રોહિકા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'લગદાણા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાસણા (ના)','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાસણા ઢેઢાલ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શિયાળ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સરલા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાંકોડ','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાકોદરા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાલજડા','taluka_id' => '2','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હસનનગર','taluka_id' => '2','distric_id' => '1']);
        
        $this->insert('cities',['name'=> 'અડવાળ','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'અણી ભીમજી','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'આક઼રુ','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઉંચડી','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કોટડા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કોઠડીયા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખડોળ','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખરડ','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખસ્તા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગુંજાર','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગલસાણા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઘંઘુકા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'છસીયાણા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'છારોડીયા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જશાપર','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જસ્કા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જાલીયા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝાંઝરકા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝીંઝર','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'તગડી','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ધોળી','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાનાત્રાડીયા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પચ્છમ','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પડાણા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પરબડી','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પીપળ','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ફતેપુર','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ફેદરા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બાજરડા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભલગામડા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોટાત્રાડીયા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોરસીયા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રંગપુર','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રતનપુર','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાયકા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રોજકા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વખતપર','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાગડ','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાસણા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સરવાળ','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાલાસર','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હડાળા','taluka_id' => '4','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હરિપુરા','taluka_id' => '4','distric_id' => '1']);

        $this->insert('cities',['name'=> 'આણંદપુર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'આંબલી','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઓતારીયા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કમીયાળા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાદીપુર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કામાતળાવ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાસિંદ્રા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખુણ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગાંફ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગોગલા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગોરાસુ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઘનાળા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઘોલેરા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચેર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝાંખી','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નવાગામ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પાંચી','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પીંપળી','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બુરાનપુર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બાવલીયારી','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભડીયાદ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભાણગઢ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ભીમતળાવ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મુંડી','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મહાદેવપુરા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મીંગલપુર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાહતળાવ','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાલિંદા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શેલા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાંગાસર','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાંઢીડા','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સોઢી','taluka_id' => '5','distric_id' => '1']);
        $this->insert('cities',['name'=> 'હેબતપુર','taluka_id' => '5','distric_id' => '1']);


        $this->insert('cities',['name'=> 'અણીયાળી-કસ્બાતી','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'અણીયાળી-કાઠી','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'અલઉ','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'અલમપુર','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઊમરાળા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કુંડલી','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કેરીયા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કીનારા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખસ','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખોખરનેશ','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગઢીયા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગુંદા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ગોધાવટા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચંદરવા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચારણકી','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'જાળીલા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દેરડી','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દેવગાણા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'દેવળીયા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ધારપીંપળા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાગનેશ','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાનીવાવડી','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પાટણા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પાણવી','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બગડ','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બુબાવાવ','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બરાનીયા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બોડીયા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'માલણપુર','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'મોટીવાવડી','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાજપરા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાણપુર','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વેજલકા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સુંદરીયાણા','taluka_id' => '12','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાંગણપુર','taluka_id' => '12','distric_id' => '1']);
        


       
        $this->insert('cities',['name'=> 'અંકેવાળીયા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કુંડળ','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'કાપડીયાળી','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખડસલીયા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખમીદાણા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ખાંભડા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચાંચરીયા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ચોકડી','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઝરવલીયા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ટીંબલા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'ઢાઢોદર','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નભોઇ','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'નાવડા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પીપરીયા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'પોલારપુર','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બરવાળા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'બેલા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રેફડા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રાણપરી','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રામ઼પરા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'રોજીદ','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વહીયા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'વાઢેલા','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'શાહપુર','taluka_id' => '13','distric_id' => '1']);
        $this->insert('cities',['name'=> 'સાળંગપુર','taluka_id' => '13','distric_id' => '1']);
        
        
        
        

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m240420_094711_insert_data_cities_table cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m240420_094711_insert_data_cities_table cannot be reverted.\n";

        return false;
    }
    */
}
